variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true

stages:
  - build
  - deploy

image: maven:3-openjdk-17

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - echo "Starting build process..."
    - 'mvn $MAVEN_CLI_OPTS clean install -U'
  artifacts:
    paths:
      - target/
deploy:jdk17:
  stage: deploy
  script:
    - echo "Checking for CI settings file..."
    - if [ ! -f ci_settings.xml ]; then
      echo "CI settings missing! Please follow the instructions at https://docs.gitlab.com/ee/user/packages/maven_repository/index.html#create-maven-packages-with-gitlab-cicd";
      exit 1;
      fi
    - echo "Starting deploy process..."
    - 'mvn $MAVEN_CLI_OPTS deploy --settings ci_settings.xml'